version: '3.8'

services:
  db:
    build: .
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: airline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    command: >
      bash -c "while ! pg_isready -h db -U postgres; do sleep 1; done &&
      sleep 5 &&
      ./reservas 10 5 \"SERIALIZABLE\""
    environment:
      DB_CONNECTION: "dbname=airline user=postgres password=postgres host=db client_encoding=UTF8"

volumes:
  postgres_data: